### ISSUE TITLE
Route grouping issue with Fastify v3 + TypeScript?

### ISSUE THREAD

**Issue by huming2207** [fastify/help#215]
Hi there, 

I'm trying to migrate my project to Fastify v3. But I've got a TypeScript typing problem with adding route grouping with `fastify.register()`.

Firstly, here's my project repo: https://github.com/huming2207/datasheep-api/tree/feature/fastify-v3/src

What happened is that I have some handlers trying to group to different URL paths by using `fastify.register()`. It works fine before when I was using Fastify v2.15. 

But now here's what I've got:

![image](https://user-images.githubusercontent.com/4463497/87219911-929b7000-c3a2-11ea-81fe-9acbc0ebbc75.png)

The related code is at: https://github.com/huming2207/datasheep-api/blob/feature/fastify-v3/src/handlers/ProtectedRequests.ts#L24

...and: https://github.com/huming2207/datasheep-api/blob/feature/fastify-v3/src/handlers/EventHandler.ts#L104

What I understood is, it says the default `FastifyInstance` can't be assigned to the `.register()`'s `FastifyInstance<RawServerBase, RawRequestDefaultExpression<RawServerBase>, RawReplyDefaultExpression<RawServerBase>>`. How can I solve this issue? Please provide me some suggestions, thanks!

Here's my environment setup:

- *Node version*: 12.18
- *fastify version*: 3.0.0
- *OS*: Linux
- TypeScript: 3.9.6

Regards,
Jackson

**Comment by mcollina** [comment]
@Ethan-Arrowood @delvedor would you mind to take a look?

I have a feeling this is tied to https://github.com/fastify/fastify/issues/2397.

**Comment by huming2207** [comment]
Hi @mcollina 

Yea I think it's similar. Please fix it soon. Thanks.

Regards,
Jackson

**Comment by mcollina** [comment]
> Please fix it soon.

One of the key principles of the Fastify community is that we help each other in maintaining this. You can send a PR if you need it _sooner_ than what anybody else could come up with a solution/fix.

**Comment by huming2207** [comment]
@mcollina Yep I think I've found a way. Maybe just change the `plugin.d.ts` to something like this:

![image](https://user-images.githubusercontent.com/4463497/87221103-e9a64280-c3ac-11ea-8650-9e480e5d2771.png)

I will file a PR soon if you think it's a good idea.

**Comment by mcollina** [comment]
I can't spot the difference, send a PR.
I've also published v3.0.1 which might contain a fix for this already.

**Comment by huming2207** [comment]
Hi @mcollina 

Just tried v3.0.1, still no luck:

![image](https://user-images.githubusercontent.com/4463497/87222372-786b8d00-c3b6-11ea-8c1c-1f94cb3137d8.png)

What I mean is that we should consider adding a second parameter for the `FastifyPlugin` for setting the default server type, like this:

```typescript
/**
 * FastifyPluginCallback
 *
 * Fastify allows the user to extend its functionalities with plugins. A plugin can be a set of routes, a server decorator or whatever. To activate plugins, use the `fastify.register()` method.
 */
export type FastifyPluginCallback<Options extends FastifyPluginOptions = {}, Server extends RawServerBase = RawServerDefault> = (
  instance: FastifyInstance<Server, RawRequestDefaultExpression<Server>, RawReplyDefaultExpression<Server>>,
  opts: Options,
  next: (err?: Error) => void
) => void

/**
 * FastifyPluginAsync
 *
 * Fastify allows the user to extend its functionalities with plugins. A plugin can be a set of routes, a server decorator or whatever. To activate plugins, use the `fastify.register()` method.
 */
export type FastifyPluginAsync<Options extends FastifyPluginOptions = {}, Server extends RawServerBase = RawServerDefault> = (
  instance: FastifyInstance<Server, RawRequestDefaultExpression<Server>, RawReplyDefaultExpression<Server>>,
  opts: Options
) => Promise<void>;
```

This fix works for me anyway.

I will file a PR if you think it's okay.
 
Jackson

**Comment by mcollina** [comment]
Go for it

**Comment by mcollina** [comment]
Remember to add a test for it (look in test/types)

**Comment by huming2207** [comment]
@mcollina sure, working on it now

**Comment by huming2207** [comment]
Hi @mcollina 

Done, please review it. Thanks!

Jackson

**Comment by huming2207** [comment]
Should be all good now. Thanks for your help!

**Comment by mcollina** [comment]
Thank you! 🎉
